import 'fake-indexeddb/auto';
import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {AvisosStore,filterAvisos} from '../src/avisos-store.js';
import {AvisosModule} from '../src/avisos-ui.js';
import {Vault} from '../src/vault.js';
test('Avisos: datos parciales, seis evidencias, copia, conflicto y retirada con conservación',async()=>{
 const vault=new Vault();await vault.open();await vault.unlock('12345678');const store=new AvisosStore(vault);
 let draft=await store.save(store.create('provider'));const created=draft.createdAt;
 draft.problem='Taladros fuera de posición';draft.counterparty='Proveedor Prueba';draft=await store.save(draft);
 assert.equal(draft.code,'');assert.equal(draft.createdAt,created);assert.equal(draft.status,'Borrador');
 const original='data:image/png;base64,'+'YWJj'.repeat(3000);
 draft=await store.addPhotos(draft,Array.from({length:6},(_,i)=>({id:'p'+i,data:original,mime:'image/png',size:9000,name:'Foto '+i,comment:'Detalle '+i,source:'gallery'})));
 draft=await store.addPhotos(draft,[draft.photos[0]]);assert.equal(draft.photos.length,6);
 await assert.rejects(()=>store.addPhotos(draft,[{data:original,mime:'image/png'},{data:'data:text/plain;base64,YQ==',mime:'text/plain'}]),/imagen/);assert.equal((await store.get(draft.id)).photos.length,6);
 const stale=structuredClone(draft);draft=await store.retirePhoto(draft,'p2');
 assert.equal(draft.photos.length,5);assert.equal(draft.retiredPhotos[0].data,original);assert.equal(draft.retiredPhotos[0].comment,'Detalle 2');
 stale.problem='Edición vieja';await assert.rejects(()=>store.save(stale),/cambió/);assert.equal((await store.get(draft.id)).problem,'Taladros fuera de posición');
 const backup=await vault.backup();assert(!JSON.stringify(backup).includes('Taladros'));
 const rows=await vault.inspectBackup(backup,'12345678');const restored=rows.find(x=>x.id===draft.id);
 assert.equal(restored.photos.length,5);assert.equal(restored.photos[4].data,original);assert.equal(restored.retiredPhotos.length,1);
 assert.equal(filterAvisos(rows,{text:'proveedor taladros',type:'provider'}).length,1);assert.equal(filterAvisos(rows,{type:'customer'}).length,0);
 vault.db.close();
});
test('Avisos UI: guardado al avanzar, cámara posterior al borrador y salida bloqueada ante fallo',async()=>{
 const dom=new JSDOM('<main id="root"></main>',{url:'http://localhost'});const doc=dom.window.document,root=doc.querySelector('#root');
 const records=new Map();let rejectSave=false,delayedResolve=null,pauseSave=false;
 const vault={list:async()=>[...records.values()].map(x=>structuredClone(x)),get:async id=>structuredClone(records.get(id)),put:async(id,value)=>{if(rejectSave)throw Error('Guardado de prueba fallido');if(pauseSave){pauseSave=false;await new Promise(resolve=>delayedResolve=resolve);}value._revision=(value._revision||0)+1;records.set(id,structuredClone(value));}};
 const store=new AvisosStore(vault),messages=[];let capture=0;
 const ui=new AvisosModule({root,store,say:s=>messages.push(s),title:()=>{},beginCapture:async id=>{capture++;assert(records.has(id));assert.equal(records.get(id).problem,'Defecto detectado');},finishCapture:async()=>{}});
 const $=s=>root.querySelector(s);
 await ui.newDraft('customer');$('#avProblem').value='Defecto detectado';$('#avProblem').dispatchEvent(new dom.window.Event('input'));
 await ui.flush();ui.step=2;ui.renderEditor();await ui.pickPhotos(false);assert.equal(capture,1);
 ui.step=1;ui.renderEditor();$('#avName').value='Primera';$('#avName').dispatchEvent(new dom.window.Event('input'));
 pauseSave=true;const saving=ui.perform(()=>ui.saveDraft());await new Promise(resolve=>setTimeout(resolve,0));
 $('#avName').value='Última';$('#avName').dispatchEvent(new dom.window.Event('input'));delayedResolve();await saving;await ui.prepareLeave();assert.equal(records.get(ui.draft.id).name,'Última');
 $('#avAction').value='Retener lote';$('#avAction').dispatchEvent(new dom.window.Event('input'));rejectSave=true;
 await assert.rejects(()=>ui.prepareLeave(),/fallido/);assert.equal(ui.view,'editor');assert.equal($('#avAction').value,'Retener lote');assert(ui.dirty);
 rejectSave=false;await ui.prepareLeave();await ui.goBack();assert.equal(ui.view,'menu');await ui.openDraft([...records.keys()][0]);assert.equal($('#avAction').value,'Retener lote');
 await ui.prepareLeave();dom.window.close();
});
